# Site settings
title: Ozznotes
description: >
  This is a blog with random OpenStack and Linux related notes so I don't
  forget what I did.
url: 'http://jaormx.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Juan Antonio "Ozz" Osorio Robles'
  #email:
  twitter_username: jaosorior
  github_username:  JAORMX
  linkedin_username:  jaosorior

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
