# Site settings
title: Ozznotes
description: >
  This is a blog with random OpenStack and Linux related notes so I don't
  forget things.

  If you find something inaccurate or that could be fixed, please file a bug
  report <a href='https://github.com/JAORMX/JAORMX.github.io/issues'>here.</a>
url: 'http://jaormx.github.io'
baseurl: '/'

twitter_username: jaosorior
github_username:  JAORMX
linkedin_username:  jaosorior

# Build settings
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png', 'create_post.py']

theme: jekyll-theme-midnight
