# Site settings
title: Ozznotes
description: >
  This is a blog with random OpenShift, Kubernetes, OpenStack and Linux related
  notes so I don't forget things.

  If you find something inaccurate or that could be fixed, please file a bug
  report <a href='https://github.com/JAORMX/JAORMX.github.io/issues'>here.</a>
url: 'http://jaormx.github.io'
baseurl: '/'

author: Juan Antonio Osorio Robles
twitter_username: jaosorior
twitter:
  username: jaosorior
  card: "summary"
  description: "AKA Ozz: Mexican Open Source Software developer. OpenShift, OpenStack, Beer, Heavy Metal and my beard."
github_username:  JAORMX
linkedin_username:  jaosorior
google_analytics: UA-124742268-1

image: /images/cup.jpg

# Build settings
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins:
- 'jekyll-feed'
- 'jekyll-paginate'
- 'jekyll-seo-tag'
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png', 'create_post.py', 'templates', 'vendor']

theme: jekyll-theme-hacker
