# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The blog of Ozz
#email: @.com
description: > # this means to ignore newlines until "baseurl:"
  This is a blog with random OpenStack and Linux related notes so I don't
  forget what I did.
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jaosorior
github_username:  JAORMX

# Build settings
markdown: kramdown
